services:
  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    environment:
      - CATALOG_CATALOG__IMPL=org.apache.iceberg.hadoop.HadoopCatalog
      - CATALOG_WAREHOUSE=file:///warehouse
      - CATALOG_IO__IMPL=org.apache.iceberg.hadoop.HadoopFileIO
    volumes:
      - ./warehouse:/warehouse
    ports:
      - "8181:8181"

  trino:
    build:
      context: ./trino
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - ./warehouse:/warehouse
    ports:
      - "8081:8080"
    depends_on:
      - iceberg-rest